export interface CurrencyMeta {
  name: string;
  symbol: string;
}

export const CURRENCY_META: Record<string, CurrencyMeta> = {
  ADA: { name: "Cardano", symbol: "ADA" },
  AED: { name: "UAE Dirham", symbol: "د.إ" },
  AFN: { name: "Afghan Afghani", symbol: "؋" },
  ALL: { name: "Albanian Lek", symbol: "L" },
  AMD: { name: "Armenian Dram", symbol: "֏" },
  ANG: { name: "Netherlands Antillean Guilder", symbol: "ƒ" },
  AOA: { name: "Angolan Kwanza", symbol: "Kz" },
  ARS: { name: "Argentine Peso", symbol: "$" },
  AUD: { name: "Australian Dollar", symbol: "A$" },
  AVAX: { name: "Avalanche", symbol: "AVAX" },
  AWG: { name: "Aruban Florin", symbol: "ƒ" },
  AZN: { name: "Azerbaijani Manat", symbol: "₼" },
  BAM: { name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
  BBD: { name: "Barbadian Dollar", symbol: "Bds$" },
  BDT: { name: "Bangladeshi Taka", symbol: "৳" },
  BGN: { name: "Bulgarian Lev", symbol: "лв" },
  BHD: { name: "Bahraini Dinar", symbol: ".د.ب" },
  BCH: { name: "Bitcoin Cash", symbol: "BCH" },
  BIF: { name: "Burundian Franc", symbol: "Fr" },
  BMD: { name: "Bermudian Dollar", symbol: "$" },
  BNB: { name: "BNB", symbol: "BNB" },
  BND: { name: "Brunei Dollar", symbol: "B$" },
  BOB: { name: "Bolivian Boliviano", symbol: "Bs." },
  BRL: { name: "Brazilian Real", symbol: "R$" },
  BSD: { name: "Bahamian Dollar", symbol: "B$" },
  BTC: { name: "Bitcoin", symbol: "₿" },
  BTN: { name: "Bhutanese Ngultrum", symbol: "Nu" },
  BWP: { name: "Botswana Pula", symbol: "P" },
  BYN: { name: "Belarusian Ruble", symbol: "Br" },
  BZD: { name: "Belize Dollar", symbol: "BZ$" },
  CAD: { name: "Canadian Dollar", symbol: "C$" },
  CDF: { name: "Congolese Franc", symbol: "Fr" },
  CHF: { name: "Swiss Franc", symbol: "Fr" },
  CLP: { name: "Chilean Peso", symbol: "$" },
  CNY: { name: "Chinese Yuan", symbol: "¥" },
  COP: { name: "Colombian Peso", symbol: "$" },
  CRC: { name: "Costa Rican Colón", symbol: "₡" },
  CUP: { name: "Cuban Peso", symbol: "$" },
  CVE: { name: "Cape Verdean Escudo", symbol: "$" },
  CZK: { name: "Czech Koruna", symbol: "Kč" },
  DJF: { name: "Djiboutian Franc", symbol: "Fr" },
  DKK: { name: "Danish Krone", symbol: "kr" },
  DOGE: { name: "Dogecoin", symbol: "Ð" },
  DOP: { name: "Dominican Peso", symbol: "RD$" },
  DOT: { name: "Polkadot", symbol: "DOT" },
  DZD: { name: "Algerian Dinar", symbol: "دج" },
  EGP: { name: "Egyptian Pound", symbol: "E£" },
  ERN: { name: "Eritrean Nakfa", symbol: "Nfk" },
  ETB: { name: "Ethiopian Birr", symbol: "Br" },
  ETH: { name: "Ethereum", symbol: "Ξ" },
  EUR: { name: "Euro", symbol: "€" },
  FJD: { name: "Fijian Dollar", symbol: "FJ$" },
  FKP: { name: "Falkland Islands Pound", symbol: "£" },
  GBP: { name: "British Pound", symbol: "£" },
  GEL: { name: "Georgian Lari", symbol: "₾" },
  GHS: { name: "Ghanaian Cedi", symbol: "₵" },
  GIP: { name: "Gibraltar Pound", symbol: "£" },
  GMD: { name: "Gambian Dalasi", symbol: "D" },
  GNF: { name: "Guinean Franc", symbol: "Fr" },
  GTQ: { name: "Guatemalan Quetzal", symbol: "Q" },
  GYD: { name: "Guyanese Dollar", symbol: "G$" },
  HKD: { name: "Hong Kong Dollar", symbol: "HK$" },
  HYPE: { name: "Hyperliquid", symbol: "HYPE" },
  HNL: { name: "Honduran Lempira", symbol: "L" },
  HRK: { name: "Croatian Kuna", symbol: "kn" },
  HTG: { name: "Haitian Gourde", symbol: "G" },
  HUF: { name: "Hungarian Forint", symbol: "Ft" },
  IDR: { name: "Indonesian Rupiah", symbol: "Rp" },
  ILS: { name: "Israeli New Shekel", symbol: "₪" },
  INR: { name: "Indian Rupee", symbol: "₹" },
  IQD: { name: "Iraqi Dinar", symbol: "ع.د" },
  IRR: { name: "Iranian Rial", symbol: "﷼" },
  ISK: { name: "Icelandic Króna", symbol: "kr" },
  JMD: { name: "Jamaican Dollar", symbol: "J$" },
  JOD: { name: "Jordanian Dinar", symbol: "JD" },
  JPY: { name: "Japanese Yen", symbol: "¥" },
  KES: { name: "Kenyan Shilling", symbol: "KSh" },
  KGS: { name: "Kyrgyzstani Som", symbol: "с" },
  KHR: { name: "Cambodian Riel", symbol: "៛" },
  KMF: { name: "Comorian Franc", symbol: "Fr" },
  KPW: { name: "North Korean Won", symbol: "₩" },
  KRW: { name: "South Korean Won", symbol: "₩" },
  KWD: { name: "Kuwaiti Dinar", symbol: "KD" },
  KYD: { name: "Cayman Islands Dollar", symbol: "CI$" },
  KZT: { name: "Kazakhstani Tenge", symbol: "₸" },
  LAK: { name: "Laotian Kip", symbol: "₭" },
  LBP: { name: "Lebanese Pound", symbol: "L£" },
  LEO: { name: "LEO Token", symbol: "LEO" },
  LINK: { name: "Chainlink", symbol: "LINK" },
  LKR: { name: "Sri Lankan Rupee", symbol: "Rs" },
  LRD: { name: "Liberian Dollar", symbol: "L$" },
  LSL: { name: "Lesotho Loti", symbol: "L" },
  LTC: { name: "Litecoin", symbol: "Ł" },
  LYD: { name: "Libyan Dinar", symbol: "LD" },
  MAD: { name: "Moroccan Dirham", symbol: "MAD" },
  MATIC: { name: "Polygon", symbol: "MATIC" },
  MDL: { name: "Moldovan Leu", symbol: "L" },
  MGA: { name: "Malagasy Ariary", symbol: "Ar" },
  MKD: { name: "Macedonian Denar", symbol: "ден" },
  MMK: { name: "Myanmar Kyat", symbol: "K" },
  MNT: { name: "Mongolian Tögrög", symbol: "₮" },
  MOP: { name: "Macanese Pataca", symbol: "P" },
  MRU: { name: "Mauritanian Ouguiya", symbol: "UM" },
  MUR: { name: "Mauritian Rupee", symbol: "Rs" },
  MVR: { name: "Maldivian Rufiyaa", symbol: "Rf" },
  MWK: { name: "Malawian Kwacha", symbol: "MK" },
  MXN: { name: "Mexican Peso", symbol: "$" },
  MYR: { name: "Malaysian Ringgit", symbol: "RM" },
  MZN: { name: "Mozambican Metical", symbol: "MT" },
  NAD: { name: "Namibian Dollar", symbol: "N$" },
  NGN: { name: "Nigerian Naira", symbol: "₦" },
  NIO: { name: "Nicaraguan Córdoba", symbol: "C$" },
  NOK: { name: "Norwegian Krone", symbol: "kr" },
  NPR: { name: "Nepalese Rupee", symbol: "Rs" },
  NZD: { name: "New Zealand Dollar", symbol: "NZ$" },
  OMR: { name: "Omani Rial", symbol: "ر.ع." },
  PAB: { name: "Panamanian Balboa", symbol: "B/." },
  PEN: { name: "Peruvian Sol", symbol: "S/." },
  PGK: { name: "Papua New Guinean Kina", symbol: "K" },
  PHP: { name: "Philippine Peso", symbol: "₱" },
  PKR: { name: "Pakistani Rupee", symbol: "Rs" },
  PLN: { name: "Polish Złoty", symbol: "zł" },
  PYG: { name: "Paraguayan Guaraní", symbol: "₲" },
  QAR: { name: "Qatari Riyal", symbol: "ر.ق" },
  RON: { name: "Romanian Leu", symbol: "lei" },
  RSD: { name: "Serbian Dinar", symbol: "din" },
  RUB: { name: "Russian Ruble", symbol: "₽" },
  RWF: { name: "Rwandan Franc", symbol: "Fr" },
  SAR: { name: "Saudi Riyal", symbol: "ر.س" },
  SBD: { name: "Solomon Islands Dollar", symbol: "SI$" },
  SCR: { name: "Seychellois Rupee", symbol: "Rs" },
  SDG: { name: "Sudanese Pound", symbol: "ج.س." },
  SEK: { name: "Swedish Krona", symbol: "kr" },
  SGD: { name: "Singapore Dollar", symbol: "S$" },
  SHP: { name: "Saint Helena Pound", symbol: "£" },
  SLL: { name: "Sierra Leonean Leone", symbol: "Le" },
  SOL: { name: "Solana", symbol: "◎" },
  SOS: { name: "Somali Shilling", symbol: "Sh" },
  SRD: { name: "Surinamese Dollar", symbol: "SR$" },
  STN: { name: "São Tomé and Príncipe Dobra", symbol: "Db" },
  SVC: { name: "Salvadoran Colón", symbol: "₡" },
  SYP: { name: "Syrian Pound", symbol: "£S" },
  SZL: { name: "Swazi Lilangeni", symbol: "L" },
  THB: { name: "Thai Baht", symbol: "฿" },
  TJS: { name: "Tajikistani Somoni", symbol: "SM" },
  TMT: { name: "Turkmenistan Manat", symbol: "T" },
  TND: { name: "Tunisian Dinar", symbol: "DT" },
  TON: { name: "Toncoin", symbol: "💎" },
  TOP: { name: "Tongan Paʻanga", symbol: "T$" },
  TRY: { name: "Turkish Lira", symbol: "₺" },
  TRX: { name: "TRON", symbol: "TRX" },
  TTD: { name: "Trinidad and Tobago Dollar", symbol: "TT$" },
  TWD: { name: "New Taiwan Dollar", symbol: "NT$" },
  TZS: { name: "Tanzanian Shilling", symbol: "Sh" },
  UAH: { name: "Ukrainian Hryvnia", symbol: "₴" },
  UGX: { name: "Ugandan Shilling", symbol: "Sh" },
  USD: { name: "U.S. Dollar", symbol: "$" },
  USDC: { name: "USD Coin", symbol: "USDC" },
  USDT: { name: "Tether", symbol: "₮" },
  UYU: { name: "Uruguayan Peso", symbol: "$U" },
  UZS: { name: "Uzbekistani Som", symbol: "so'm" },
  VES: { name: "Venezuelan Bolívar", symbol: "Bs.S" },
  VND: { name: "Vietnamese Đồng", symbol: "₫" },
  VUV: { name: "Vanuatu Vatu", symbol: "Vt" },
  WST: { name: "Samoan Tālā", symbol: "T" },
  XAF: { name: "CFA Franc BEAC", symbol: "Fr" },
  XAU: { name: "Gold (Troy Ounce)", symbol: "Au" },
  XAUT: { name: "Tether Gold", symbol: "XAUt" },
  XCD: { name: "East Caribbean Dollar", symbol: "EC$" },
  XLM: { name: "Stellar", symbol: "XLM" },
  XMR: { name: "Monero", symbol: "XMR" },
  XOF: { name: "CFA Franc BCEAO", symbol: "Fr" },
  XPF: { name: "CFP Franc", symbol: "Fr" },
  XRP: { name: "XRP", symbol: "XRP" },
  YER: { name: "Yemeni Rial", symbol: "﷼" },
  ZAR: { name: "South African Rand", symbol: "R" },
  ZMW: { name: "Zambian Kwacha", symbol: "ZK" },
  ZWL: { name: "Zimbabwean Dollar", symbol: "Z$" },
};

export function getCurrencyMeta(code: string): CurrencyMeta {
  return CURRENCY_META[code] ?? { name: code, symbol: code };
}

/** "USD - U.S. Dollar  $" */
export function formatCurrencyLabel(code: string): string {
  const meta = getCurrencyMeta(code);
  return `${code} — ${meta.name}  ${meta.symbol}`;
}
